version: "3.8"
services:
    db:
      image: "microsoft/mssql-server-linux:2017-latest"
      ports:
        - "1433:1433"
      environment:
        ACCEPT_EULA: "Y"
        SA_PASSWORD: "Your_password123"
        DATABASE: "Test"

    integration-tests:
      build:
        context: .
        dockerfile: Dockerfile
      depends_on:
        - db
      env_file:
        - .env
      command: ["./wait-for-it.sh",
                "db:1433",
                "-t",
                "120",
                "--",
                "dotnet", "test", "-s", "./InfiniteCalendar.Test/test.runsettings"]
