name: DotNet Test

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
  
      - name: Execute tests
        run: docker-compose up --exit-code-from integration-tests integration-tests
